name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Run a single-line script
      - name: Run a one-line script
        run: echo Hello, world!

      # Run a multi-line script
      - name: Run a multi-line script
        run: |
          echo Add steps to build,
          echo test, and deploy your project.
